---
- name: Install Mysql (mariadb) & MySQL-python
  yum:
    name: mariadb-server,mariadb,MySQL-python
    state: latest

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable SElinux
  selinux:
    state: disabled

- name: Ensure mariadb is running
  systemd:
    state: started
    enabled: yes
    name: mariadb
  notify: restart mariadb

- name: Create WordPress db user
  mysql_user: name={{wp_db_user}} password={{wp_db_password}} priv={{wp_db_name}}.*:ALL host='%' state=present

- name: Create WordPress db
  mysql_db: name={{wp_db_name}} state=present