---
- name: Install Mariadb & needed packages
  yum:
    name:
      - mariadb
      - mariadb-server
      - MySQL-python
    state: latest

- name: Ensure mariadb is running
  service:
    name: mariadb
    state: started
    enabled: true
  notify: restart mariadb

# Removes all anonymous user accounts
- mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Create new database 'wordpress'
  mysql_db:   
    name: "{{ wp_db_name }}"
    state: present

- mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
