---
- hosts: webservers
  remote_user: vagrant

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: install FTP server
      yum:
        name: vsftpd
        state: latest

    - name: install mariadb-server and mariadb
      yum:
        name: mariadb-server,mariadb
        state: latest

    - name: install Apache
      yum:
        name: httpd
        state: latest

    - name: install Php and modules
      yum:
        name: php, php-mysql
        state: latest

    - name: start httpd.service
      systemd:
        state: started
        name: httpd

    - name: start mariadb.service
      systemd:
        state: started
        name: mariadb
