---
- hosts: webservers
  remote_user: vagrant

  tasks:
    - name: Creates directory /var/www/html/wp-content/uploads
      file:
        path: /var/www/html/wp-content/uploads
        state: directory

    - name: Unarchive a file that needs to be downloaded
      unarchive:
        src: http://wordpress.org/latest.tar.gz
        dest: /var/www
        remote_src: yes
