---
- name: Install Apache, php & php-mysql
  yum:
    name: httpd,php,php-mysql
    state: latest

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable SElinux
  selinux:
    state: disabled

- name: Make sure Apache is running
  systemd:
    state: started
    enabled: yes
    name: httpd
  notify: restart apache