---
- name: Download and unarchive Wordpress
  unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Create group "wordpress"
  group:
    name: wordpress
    state: present

- name: Create user "wordpress"
  user:
    name: wordpress
    groups: wordpress

- name: Copy wordpress conf
  template:
    src: templates/wp-config.php
    dest: /var/www/html/wordpress

- name: Change "/var/www/html/wordpress/" permissions
  file: path=/var/www/html/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t